# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shop' do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 4.0.0-beta2'
  pod 'Masonry', '~> 1.0.2'
  pod 'MJExtension', '~> 3.0.13'
  pod 'LFLiveKit'

end
